DATASET:
  MODEL_SAVE_DIR: ./model_outputs/
  TRAIN_CSV: ./data/segmentation/train_segmentation.csv
  VAL_CSV: ./data/segmentation/val_segmentation.csv
DATASET_CUSTOME:
  INPUT_LENGTH: 7168
  LEADS:
  - I
  - II
  - III
  - aVR
  - aVL
  - aVF
  - V1
  - V2
  - V3
  - V4
  - V5
  - V6
  OUT_C: 3
  TARGET_NAMES:
  - baseline
  - use
  - non
MODEL:
  DEPTHS:
  - 2
  - 2
  - 3
  - 2
  Denoise_Mode: true
  EMBED_DIM: 24
  N_HEADS:
  - 3
  - 6
  - 12
  - 24
  PATCH_SIZE: 2
  WINDOW_SIZE: 112
OPTIM:
  BATCH_SIZE: 64
  CE_ratio: 0.0
  Dice_ratio: 0.5
  Focal_ignore_idx: -100
  Focal_ratio: 0.5
  LR_INITIAL: 0.001
  LR_MIN: 1.0e-06
  NUM_EPOCHS: 600
RUN_DATE: 2024_11_28-14_52
SAVE_DIR: ./model_outputs/segmentation_2024_11_28-14_52/
TRY_TIME: segmentation
